### ISSUE TITLE
Error saving an edited record

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#10]
I get the following error when I try to edit and save a record

`[2018-07-10 02-58-01] Fatal Error: Cannot use string offset as an array in /var/www/html/micka/php/app/model/RecordModel.php(990) : eval()'d code:124  @  http://visorgeo.ambientebogota.gov.co/micka/es/record/save/agente_participacion_ambiental  @@  exception--2018-07-10--02-58--7fd0440ff9.html`

**Comment by skafka** [comment]
Please, send me the exception file php/logs/exception--2018-07-10--02-58--7fd0440ff9.html . It looks like an attempt to edit imported XML file with non-standard elements.

**Comment by samtux** [comment]
Thank @skafka  here the link:

https://gist.githubusercontent.com/samtux/67bfbe783888bf98a20799f9c8dfc5a6/raw/7f607cd6e4e0f16e54c49035e53d34b829c46078/exception--2018-07-10--02-58--7fd0440ff9.html

**Comment by samtux** [comment]
The next is the error in master code:

` PHP Warning: Illegal string offset 'lang' in /var/www/html/micka/php/app/model/RecordModel.php(1021) : eval()'d code:34`

[exception--2019-01-07--22-53--50e7eddc26.html](https://gistcdn.githack.com/samtux/7b2d439814f35b34e9a8349cb48fc9f3/raw/4f7e5f0dfbc3b41486f7c68d3a80cb53e717b6da/exception--2019-01-07--22-53--50e7eddc26.html)

**Comment by samtux** [comment]
a possible solution but with errors is the following:

https://github.com/hsrs-cz/Micka/blob/828ee3345bc411829be775b33d81339cf8c18303/php/app/model/RecordModel.php#L1021

by:

```php
${ $eval_text};
```
according to the following post:

https://stackoverflow.com/questions/7874363/evald-code-on-line-xx/7874446#7874446

**Comment by skafka** [comment]
The proposed solution is not satisfactory. We are working on the improved robust version.
