### ISSUE TITLE
Set global proxy variables

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#11]
Is it possible to set proxy variables globally for the Internet connection? 

I find the variables CONNECTION_PROXY and CONNECTION_PORT, but I can't find where to define them.

Thanks

**Comment by samtux** [comment]
A possible solution would be to define the environment variables in PHP-FPM:

```
#/etc/php/5.6/fpm/pool.d/www.conf

env[“CONNECTION_PROXY”] = 'http://<IP>'
env[“CONNECTION_PORT”] = <PORT>
```

**Comment by skafka** [comment]
Added to configuration
