### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#2]
I get the next error in Arch Linux, with PHP7 and PHP56. 

```
Nette\Application\BadRequestException #404

Cannot load presenter 'Index:Php:Search', class 'IndexModule\PhpModule\SearchPresenter' was not found. search

```
http://storage4.static.itmages.com/i/17/0819/h_1503118171_8090285_6a617069d6.png

**Comment by skafka** [comment]
Hi Samuel,

 

I will check the problem and let you know when fixed.

 

Stepan

**Comment by samtux** [comment]
Thank you very much @skafka  and thank you for sharing this excellent tool.

regards

**Comment by skafka** [comment]
fixed. See https://github.com/hsrs-cz/Micka/commit/08255fc3772d73412e77cf05bf38baa93e83bd62
