### ISSUE TITLE
Error new metadata registre 

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#3]
For all cases in create new registre metadata, report the next error:

`[2017-09-07 17-42-01] Nette\Database\DriverException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column standard_schema.is_uri does not exist LINE 2:             standard_schema.is_uri ^ #42703 in /var/www/Micka/php/vendor/nette/database/src/Database/DriverException.php:25 caused by PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column standard_schema.is_uri does not exist LINE 2:             standard_schema.is_uri ^ #42703 in /var/www/Micka/php/vendor/nette/database/src/Database/ResultSet.php:72  @  http://localhost:8281/Micka/en/record/edit/new  @@  exception--2017-09-07--23-45--e533c79ef6.html`

I use Ubuntu wiht php 7

**Comment by skafka** [comment]
fixed
