### ISSUE TITLE
Error  with Resources Capabilities

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#7]
Publishing the CSW service generates Web links to connection resources incorrectly, as shown in the following image.

The right thing would be for operations:

http://www.aulageo.cloud/Micka/csw

and is currently displayed as:

http://www.aulageo.cloud/Micka/index.php

![Micka](https://i.imgur.com/oRlipZF.png)

This generates errors when trying to make the connection to the service. Is it possible to correct the resources of operations?

Thanks.

**Comment by skafka** [comment]
fixed
