### ISSUE TITLE
Error when importing metadata with editor permissions

### ISSUE THREAD

**Issue by samtux** [hsrs-cz/Micka#9]
When the metadata is imported from a file or URL with editor permissions it generates the following error:

```
appError
Sorry, no record found.
```
![https://i.imgur.com/i6jNzZj.gif](https://i.imgur.com/i6jNzZj.gif)

With administrator permissions if you want to import metadata.

The URL metadata is: https://samtux.github.io/lagunatota_wmts/metadata/curvas_100k/iso19139.xml

**Comment by skafka** [comment]
Please, send use error logs from log folder

**Comment by samtux** [comment]
The log messages are the following in the error.log:

> [2017-10-30 16-25-20] PHP Notice: Undefined index: MD_Metadata in /var/www/Micka/php/app/model/MdXml2Array.php:316  @  http://www.aulageo.cloud/Micka/en/record/edit/new 
[2017-10-30 16-27-44] PHP Warning: XSLTProcessor::transformToXml(): I/O warning : failed to load external entity "/var/www/Micka/php/app/model/xsl/codelists_eng.xml" in /var/www/Micka/php/app/model/Csw.php:817  @  http://www.aulageo.cloud/Micka/en/

**Comment by skafka** [comment]
Hmm, it should work. Here is the imported record on our demo: https://dev.bnhelp.cz/micka-demo/es/record/basic/ES-2017-eOqa92uDi5Er_101417H01M15S 
Please try update to latest version and empty the cache (php/temp/cache) before import.

**Comment by samtux** [comment]
@skafka,  but when authenticating as "editor", it does not allow editing in the registry, in the same demo that you share, the error continues to come out:

![https://i.imgur.com/sUg3z6b.png](https://i.imgur.com/sUg3z6b.png)

```
appError

Sorry, no record found.
```
